apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlbatch-system

resources:
- "https://github.com/kubernetes-sigs/kueue/config/default?ref=v0.10.1"

labels:
- pairs:
    app.kubernetes.io/name: kueue
    app.kubernetes.io/component: controller
  includeSelectors: true

configMapGenerator:
- name: manager-config
  namespace: kueue-system
  behavior: replace
  files:
  - controller_manager_config.yaml

images:
- name: us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue
  newName: registry.k8s.io/kueue/kueue
  newTag: v0.10.1

patches:
- path: manager_resources_patch.yaml
- path: mutating_webhook_patch.yaml
- path: remove_default_namespace.yaml
- path: validating_webhook_patch.yaml
- target:
    kind: ClusterRole
    name: manager-role
  patch: |
    - op: add
      path: /rules/-
      value:
        apiGroups:
        - workload.codeflare.dev
        resources:
        - appwrappers
        verbs:
        - get
        - list
        - watch
- target:
    kind: Deployment
    name: controller-manager
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--feature-gates=LendingLimit=true"
