apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlbatch-system

resources:
- "https://github.com/project-codeflare/appwrapper/config/default?ref=v0.21.0"

images:
- name: quay.io/ibm/appwrapper
  newTag: v0.21.0

patches:
- path: manager_resources_patch.yaml
- path: config_patch.yaml